"""Init

Revision ID: 0372e8671c33
Revises: 831aa5b58f37
Create Date: 2023-12-24 23:06:10.180011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0372e8671c33'
down_revision: Union[str, None] = '831aa5b58f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio',
    sa.Column('audio_id', sa.UUID(), nullable=False),
    sa.Column('audio', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('audio_id')
    )
    op.create_table('authors',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audio_association',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('audio_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.audio_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], )
    )
    op.create_table('author_association',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], )
    )
    op.create_table('mashups',
    sa.Column('mashup_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('audio_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.audio_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mashup_id')
    )
    op.create_table('mashup_association',
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('mashup_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mashup_id'], ['mashups.mashup_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mashup_association')
    op.drop_table('mashups')
    op.drop_table('author_association')
    op.drop_table('audio_association')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('authors')
    op.drop_table('audio')
    # ### end Alembic commands ###
