"""Init

Revision ID: 8f03133930fd
Revises: 
Create Date: 2023-12-24 23:27:19.047989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f03133930fd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audio",
        "audio_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "audio_association",
        "source_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "audio_association",
        "audio_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "author_association",
        "source_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "author_association",
        "author_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "authors",
        "author_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashup_association",
        "source_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "mashup_association",
        "mashup_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "mashups",
        "mashup_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashups",
        "audio_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashups",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "source_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "sources",
        "source_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashups",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashups",
        "audio_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashups",
        "mashup_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "mashup_association",
        "mashup_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "mashup_association",
        "source_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "authors",
        "author_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "author_association",
        "author_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "author_association",
        "source_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "audio_association",
        "audio_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "audio_association",
        "source_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "audio",
        "audio_id",
        existing_type=sa.Integer(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
